site_name: ""
repo_url: https://github.com/CAREamics/careamics
repo_name: CAREamics
#edit_uri: https://github.com/CAREamics/careamics.github.io/blob/main/docs/
edit_uri: "" # disable the edit button

nav:
  - Home: index.md
  - Current State: current_state.md
  - Installation: installation.md
  - Guides:
      - Guides: guides/index.md
      - Configuration:
          - guides/configuration/index.md
          - guides/configuration/config_description.md
      - Engine:
          - guides/engine/index.md
          - guides/engine/training.md
          - guides/engine/prediction.md
      - BioImage.io:
          - guides/bmz/index.md
  - Applications:
      - Applications: applications/index.md
  - Algorithms:
      - algorithms/index.md
      - Noise2Void:
          - algorithms/n2v/index.md
  - Code Reference: reference/

theme:
  name: material
  logo: assets/banner_careamics_large.png
  favicon: assets/icon_careamics.png
  custom_dir: docs/overrides
  font: false
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

  features:
    #- navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    # - navigation.footer  # next/previous links in footer
    - navigation.content_next # next/previous links bottom of content
    # - navigation.instant # hard to use with javascript on page load
    # - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - navigation.icons

markdown_extensions:
  #- pymdownx.extra # markdown in html (includes commented extensions below)
  - attr_list
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs/overrides/.icons/octicons
  # - pymdownx.progressbar:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

plugins:
  - search

  # jupyter notebooks: https://pypi.org/project/mkdocs-jupyter/
  # - mkdocs-jupyter:
  #     no_input: False

  # Generate code documentation from other modules
  # generate .md for a python modules
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  # allow navigation from a file, used together with gen-files
  - literate-nav:
      nav_file: SUMMARY.md
  # generate docstrings
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy

  # minify files
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - stylesheets/extra.css

  # check spelling in all files, including code documentation
  - spellcheck:
      backends: # the backends you want to use
        - codespell: # or nested configs
            dictionaries: [clear, rare]

watch:
  - docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CAREamics/careamics

extra_css:
  - stylesheets/extra.css
  - stylesheets/grid_menu.css
